apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 3  # Number of pods to create
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: username/repository-name:latest  # Replace with your Docker image
          ports:
            - containerPort: 80  # Port your application listens on
          env:  # Optional: Define environment variables
            - name: ENV_VAR_NAME
              value: "value"
---
apiVersion: v1
kind: Service
metadata:
  name:

